---
- name: install_zabbix
  gather_facts: false
  hosts: zabbix
  vars:
    ansible_ssh_user: user
  become: true

  tasks:
    #    - name: "copy_zabbix"
    #      ansible.builtin.apt:
    #        url: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu22.04_all.deb
    - name: "copy_zabbix"
      ansible.builtin.get_url:
        url: wget https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu22.04_all.deb
        dest: /tmp/zabbix-release_6.2-4%2Bubuntu22.04_all.deb

    - name: Install a .deb package
      ansible.builtin.apt:
        deb: /tmp/zabbix-release_6.2-4%2Bubuntu22.04_all.deb

    - name: "install_postgresql"
      ansible.builtin.apt:
        name: postgresql
        state: present
        update_cache: true

    - name: "install___zabbix"
      ansible.builtin.apt:
        pkg:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        update_cache: true

    - name: "Create user and BD"
      ansible.builtin.shell: |
        sudo -u postgres createuser --pwprompt zabbix &&
        sudo -u postgres createdb -O zabbix zabbix &&
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz && 
        sudo -u zabbix psql zabbix && 
        sudo sed -i 's/# DBPassword=/DBPassword=zabbix/g' /etc/zabbix/zabbix_server.conf &&
        sudo sed -i 's/#        listen          8080;/listen  8080;/g' /etc/zabbix/nginx.conf &&
        sudo sed -i 's/#        server_name     example.com;/server_name  zabbix;/g' /etc/zabbix/nginx.conf &&
      args:
        executable: /bin/bash

    - name: "Start zabbix"
      ansible.builtin.systemd:
        name: zabbix-server
        state: started
        enabled: true

    - name: "Start nginx"
      ansible.builtin.systemd:
        name: nginx.service
        state: started
        enabled: true

    - name: "Start php8.1-fpm"
      ansible.builtin.systemd:
        name: php8.1-fpm.service
        state: started
        enabled: true

    - name: "zabbix-agent"
      ansible.builtin.systemd:
        name: zabbix-agent.service
        state: started
        enabled: true
